### PR TITLE
Adding loading state component

### PR DESCRIPTION
**Pull request by riichb**
## What this does
  - Created a loading spinner component off of Tash's design. 
 
## Why did I do it?
  - Wanted to showcase new loading spinner. 
 
## Follow up tasks
  - **Add it to hero section**
 
### After
Screen Shot 2019-03-25 at 1 35 25 PM

### CODE REVIEW

**Comment by riichb** [comment]
Lightening up the color 

Screen Shot 2019-03-25 at 1 54 31 PM

**Comment by riichb** [comment]
Making color one level darker

Screen Shot 2019-03-25 at 2 00 31 PM

**Comment by karstenrowe** [comment]
This is a thing of beauty—we can add to the hero in a separate PR. Merging.

**Comment by haseebjkhan** [comment]
Beautiful work.

**Pull request merged**
